### ISSUE TITLE
pino-elasticsearch & express

### ISSUE THREAD

**Issue by AnnaWykes** [pinojs/pino-elasticsearch#11]
When I run my pino piping command via a **.sh** or **.bat** file it pipes to Elasticsearch fine, but when trying to pipe directly in bash or PowerShell it doesn't work, in all of which I'm only executing "**node appexpress | pino-elasticsearch**", any ideas why?  

This only happens when working with expressjs. I can pipe to Elasticsearch fine when running a basic js file

**Comment by mcollina** [comment]
I do not think in powershell | works the same way of Unix. I'm not a poweshell user, so I can't really help you.
Let me know if you find what the problem is.

**Comment by AnnaWykes** [comment]
Yes, Powershell is a different beast, so yes | works differently. This may be a Windows issue, as that’s the operating system I have been given in my current role. I'm using Git Bash on Windows as well, and get the same result.

**Comment by AnnaWykes** [comment]
I can confirm this is a Windows issue. Managed to test on a colleagues unix machine. Thanks for responding
