### ISSUE TITLE
not working with aws elasticsearch 7.10

### ISSUE THREAD

**Issue by ferrao** [pinojs/pino-elasticsearch#110]
I seem to be hitting a similar issues to this [one](https://github.com/elastic/elasticsearch-js/issues/1519), also mentioned [here](https://github.com/elastic/elasticsearch-py/issues/1667) and [here](https://github.com/elastic/elasticsearch-py/issues/1666)

`pino-elasticsearch` depends on the elasticsearch client as:

```
 "dependencies": {
    "@elastic/elasticsearch": "^7.7.1"
  }
```
which is causing my installation to use 

```
└─┬ pino-elasticsearch@6.1.0
  └── @elastic/elasticsearch@7.15.0 
```

I understand this is not an issue with `pino-elasticsearch` itself, so I am not sure if something should be done about it.

**Comment by ferrao** [comment]
I have worked around it by pinning my elastic client version to 7.13.0 on `package.json`:

```
"scripts": {
        "preinstall": "npx npm-force-resolutions"
  },
 "resolutions": {
        "@elastic/elasticsearch": "7.13.0",
        "hpagent": "0.1.1"
  }
```

**Comment by mcollina** [comment]
This is not compatible with AWS ElasticSearch anymore.

**Comment by ferrao** [comment]
Ok, good to know @mcollina, I am trying to get away from them as well... Have been looking at [logz.io](https://logz.io/) which seems really nice, but no transport exists, any advice on some good managed ELK that I can use that works properly with the current transport?

**Comment by mcollina** [comment]
It's not our decision, it's part of the war between Elastic and AWS.

Citing them (https://github.com/elastic/elasticsearch-py/issues/1667):

> The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using Elastic Cloud for an official and formally supported hosted Elasticsearch distribution.￼

I'm not sure if @delvedor has anything to add.

I would happily see another module focusing on AWS services.
