### ISSUE TITLE
Does it run in worker_thread or the main thread?

### ISSUE THREAD

**Issue by shahinghasemi** [pinojs/pino-elasticsearch#123]
Hi, I've been testing sending logs directly to elastic in comparison to log in STDOUT and then sending it to elastic.
I created a benchmark to use this package, however the metrics aren't so promising (it gave me about 6.8k RPS). 
This is my question: If it is running on the main thread then how can I make the logs to send in worker thread instead of the main thread which the application is running on?
```
    const streamToElastic = pinoElastic({
      index: 'lernito-exam-dev',
      consistency: 'one',
      node: 'https://elasticEndPoint.com',
      auth: {
        username: 'username,
        password: 'password',
      },
      'es-version': 7,
      'flush-bytes': 3000,
    });

    streamToElastic.on('error', (error) => {
      console.error('Elasticsearch client error:', error);
    });
    streamToElastic.on('insertError', (error) => {
      console.error('Elasticsearch insert error:', error);
    });
    logger = pino(
      {
        name,
        level,
        base: undefined,
      },
      streamToElastic,
    );
```

**Comment by mcollina** [comment]
The above code runs it inside the main thread. You'll need to define it as a transport https://getpino.io/#/docs/transports to run it inside the worker_thread.
