### ISSUE TITLE
Upgrade to ElasticSearch 8

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino-elasticsearch#146]
ElasticSearch 8 now requires https for every communication. This makes the current approach we use for running tests moot.

We need some new setup and I do not have time to look into it right now.

@delvedor can you help?

**Comment by delvedor** [comment]
I've updated [elastic/elastic-github-actions](https://github.com/elastic/elastic-github-actions/pull/25) to betetr support security on by default.
While testing the code should either avoid rejecting unauthorized certs, or set `security-enabled: false` in the action settings.

**Comment by mcollina** [comment]
@Fdawgs could you take a look at this? https://github.com/fastify/fastify-elasticsearch was recently updated.

**Comment by Fdawgs** [comment]
> @Fdawgs could you take a look at this? https://github.com/fastify/fastify-elasticsearch was recently updated.

Would it just be the CI that needs an update? Not familiar with Elasticsearch at all.

**Comment by mcollina** [comment]
They switched from being http to being https by default in the latest version.
