### ISSUE TITLE
Breaking minor update due to client dependency?

### ISSUE THREAD

**Issue by nadhifikbarw** [pinojs/pino-elasticsearch#166]
Hi, I'm willing to contribute but I need versioning guideline to address the potential issue. `v6.2.0` was released using `@elastic/elasticsearch@^7.7.1` dependency. `v6.3.0` bumped this dependency to use `v8.x` Elasticsearch client instead.

According to [@elastic/elasticsearch docs](https://github.com/elastic/elasticsearch-js#compatibility), language clients are only meant to be forward compatible.

![image](https://user-images.githubusercontent.com/10264286/230947566-efcd56db-b003-497f-89ba-217ec2e110a7.png)

This introduce probable instability due to v6.3.0 minor update when user backend might still be using 7.x Elasticsearch. I think we should start performing major version matching like what [@fastify/ajv-compiler](https://github.com/fastify/ajv-compiler) does ?

Side note, I've tried running existing test suite (`master`) but with modifying dependency to use v7.13.0 client beforehand with v7.x backend, it partially fails both tests.

Update: running master branch test untouched with x7.x backed failed tests

**Comment by jsumners** [comment]
ping: @delvedor

**Comment by mcollina** [comment]
@nadhifikbarw we are having a bit of a hard time in keeping this module up to date with all the major changes in the ES client. If you'd like to help, happy to add you as a maintainer.

How would you like to proceed?

**Comment by nadhifikbarw** [comment]
@mcollina I'd be happy to do so, i haven't had enough experience in npm package management, but i'm willing to learn. Guidelines would be appreciated for some of these specific cases:

My initial idea is to reverse/deprecate 6.3 (i'm not sure how right now) but I see @elastic/elasticsearch https://www.npmjs.com/package/@elastic/elasticsearch?activeTab=versions did the same thing with their 8.2

Perform little bit of housekeeping on docs to reflect Pino >= 7 multi stream built-in support and pino-multi-stream deprecation example. Check, and test 6.2 -> 6.3 implementation and tests changes without performing client dependency major bump to 8.x and maintain 6.x for handling 7.x ES

I do want to include one special build type for 6.x that performs client version pinning to 7.13.0 as recommended by https://opensearch.org/docs/latest/clients/index/#legacy-clients which should play nice with latest and last version divergence that still support elasticsearch-oss@7.10.2 (this is my current requirement case)

Last step would be performing separate 7.x release that start supporting 8.x ES backend and client.

I do believe dropping official support for <7 should be sanest way to go. Please let me know if you have more input on this.

**Comment by sheldhur** [comment]
This PR broke reconnection :c
