### ISSUE TITLE
Content-Type header [application/vnd.elasticsearch+x-ndjson; compatible-with=8] is not supported’)

### ISSUE THREAD

**Issue by evle** [pinojs/pino-elasticsearch#188]
When I attempted to connect to the ES server 7.10 using this ES client, I encountered an error message as follows:

The "Content-Type" header ["application/vnd.elasticsearch+x-ndjson; compatible-with=8"] is not supported.

I checked package.json and found that es-plastic rely on elasticsearch.js 8+ , could this be the cause of  problems?

**Comment by mcollina** [comment]
yes it is.

**Comment by evle** [comment]
> yes it is.

Any suggestions for this ?  Many thanks in advance

**Comment by mcollina** [comment]
Nope unfortunately, upgrade your ES db.
