### ISSUE TITLE
[docs] Pino multi stream is deprecated

### ISSUE THREAD

**Issue by schuerle** [pinojs/pino-elasticsearch#189]
Pino multi stream is deprecated https://github.com/pinojs/pino-multi-stream.

Based on [npm](https://www.npmjs.com/package/pino-multi-stream):

> No longer supported. Use the multi-stream support in the latest core Pino

Docs at https://github.com/pinojs/pino-elasticsearch/blob/master/README.md#using-multiple-streams-output-to-console-and-elasticsearch should be updated accordingly.

**Comment by mcollina** [comment]
Absolutely. It's now part of pino itself: https://getpino.io/#/docs/api?id=pino-multistream. Would you like to send a PR to adjust the docs?
