### ISSUE TITLE
Constructor breaks on some JSON objects

### ISSUE THREAD

**Issue by tdeo** [pinojs/pino-elasticsearch#27]
https://github.com/pinojs/pino-elasticsearch/blob/master/pino-elasticsearch.js#L27 seems to be assuming that `Parse(...).value` is always a string or an object, but it may also a boolean, for instance:
```
> Parse('false')
Parse { err: null, value: false }
> Parse('true')
Parse { err: null, value: true }
```

This leads to the following exception:
```
TypeError: Cannot create property 'time' on boolean 'false'
at Transform.mapper (/app/node_modules/pino-elasticsearch/pino-elasticsearch.js:28:18)
```

Should I send a PR for that ?

**Comment by mcollina** [comment]
True, please send a PR. Booleans should be skipped.
