### ISSUE TITLE
Some logs are being lost

### ISSUE THREAD

**Issue by troy-lamerton** [pinojs/pino-elasticsearch#33]
When I do 3 logs in the same function, only the first one is showing in elastic search. I checked the logs.txt output so I know the logs are going into pino-elasticsearch but they're not making it into elasticsearch.

The command that starts the node server:

```bash
node ./dist | tee ../logs.txt | pino-elasticsearch --index decoder-%{DATE} --node $ES_HOST
```

The full command:

```bash
env-cmd --no-override --use-shell 'node ./dist | tee ../logs.txt | pino-elasticsearch --index decoder-%{DATE} --node $ES_HOST'
```

I can consistently reproduce this with certain functions in my code.

**Comment by mcollina** [comment]
Would you mind uploading a simplified example to reproduce?

**Comment by troy-lamerton** [comment]
After improvements on the server-side I'm now unable to reproduce this.
