### ISSUE TITLE
README: instructions in "Setup and Testing" are unclear

### ISSUE THREAD

**Issue by gr2m** [pinojs/pino-elasticsearch#63]
The docs say

> you can use the bundled `docker-compose.yml` file

But there is no `docker-compose.yml` file, there are currently five files starting matching `docker-compose-*.yml`. I'm not exactly sure what to do with that, maybe you could amend the instructions?

**Comment by gr2m** [comment]
Also I think instead of 

> You can test it by launching `node example | pino-elasticsearch`, in this project folder. You will need to have `pino-elasticsearch` installed globally.

you could say

> You can test it by launching `node example | node cli.js`, in this project folder.

**Comment by mcollina** [comment]
> But there is no docker-compose.yml file, there are currently five files starting matching docker-compose-*.yml. I'm not exactly sure what to do with that, maybe you could amend the instructions?

We use multiple docker-compose to test against different ElasticSearch versions. Can you send a PR to fix?

**Comment by gr2m** [comment]
Does the `docker-compose up` command accept an argument for a custom docker compose config filename? If so we could add something like this to make it more explicit 

```
docker-compose up --config docker-compose-v7.yml
```

If that's not possible, maybe rename one of the files to `docker-compose.yml` so it would be used by default?

Or do you want to ask the contributor to rename one of the *.yml files to `docker-compose.yml` before running `docker-compose up`?

**Comment by mcollina** [comment]
Does the docker-compose up command accept an argument for a custom docker compose config filename?

Yes, I think it is

```
docker-compose -f docker-compose-v7.yml up
```

But I can be wrong, take a look at the docs.
